- name: Deploy K3s Manifests
  hosts: servers
  become: yes
  tasks:
    - name: Create a temporary directory for K3s manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: k3s_manifests
      register: temp_dir

    - name: Download latest cert-manager manifest
      ansible.builtin.get_url:
        url: https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
        dest: "{{ temp_dir.path }}/cert-manager.yaml"
        mode: "0644"

    - name: Copy K3s manifests to the temporary directory
      ansible.builtin.copy:
        src: k3s-manifests/
        dest: "{{ temp_dir.path }}/"
        owner: root
        group: root
        mode: "0644"

    - name: Render the registry auth secret template
      ansible.builtin.template:
        src: k3s-manifests/registry-auth-secret.yaml.j2
        dest: "{{ temp_dir.path }}/registry-auth-secret.yaml"
        owner: root
        group: root
        mode: "0644"
      vars:
        REGISTRY_HTPASSWD: "{{ lookup('env', 'REGISTRY_HTPASSWD') }}"

    - name: Apply cert-manager manifest
      command: kubectl apply -f "{{ temp_dir.path }}/cert-manager.yaml"

    - name: Wait for cert-manager-webhook to be ready
      command: >
        kubectl rollout status deployment/cert-manager-webhook
        -n cert-manager --timeout=120s

    - name: Apply K3s Manifests
      command: kubectl apply -f "{{ temp_dir.path }}/" --prune --all

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
