- name: Deploy K3s Manifests
  hosts: servers
  become: yes
  tasks:
    - name: Create a temporary directory for K3s manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: k3s_manifests
      register: temp_dir

    - name: Copy K3s manifests to the temporary directory
      ansible.builtin.copy:
        src: k3s-manifests/
        dest: "{{ temp_dir.path }}/"
        owner: root
        group: root
        mode: "0644"
        
    # temporarily disabled due to not functioning right
    # - name: Render the CF API key secret template
    #   ansible.builtin.template:
    #     src: k3s-manifests/secret-cf-api-key.yaml.j2
    #     dest: "{{ temp_dir.path }}/secret-cf-api-key.yaml"
    #     owner: root
    #     group: root
    #     mode: "0644"

    - name: Apply K3s Manifests
      command: kubectl apply -f "{{ temp_dir.path }}/" --prune --all

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
