- name: Deploy Prometheus Operator
  hosts: servers
  become: yes
  tasks:
    - name: Check if monitoring namespace exists
      command: kubectl get namespace monitoring
      register: namespace_check
      ignore_errors: yes

    - name: Create monitoring namespace if not exists
      command: kubectl create namespace monitoring
      when: namespace_check.rc != 0

    - name: Add Helm repositories
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Prometheus Operator
      command: helm install prometheus-operator prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
