- name: Deploy Prometheus Operator
  hosts: servers
  become: yes
  tasks:
    - name: Create monitoring namespace
      command: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy Prometheus Operator
      command: kubectl apply -f https://github.com/prometheus-operator/prometheus-operator/releases/latest/download/bundle.yaml -n monitoring
