- name: Install Cockpit
  hosts: servers
  become: yes
  tasks:
    - name: Install Cockpit and related packages
      ansible.builtin.apt:
        name:
          - cockpit
          - cockpit-networkmanager
          - cockpit-packagekit
          - cockpit-storaged
          - cockpit-system
          - cockpit-pcp
        state: present
        update_cache: yes

    - name: Ensure Cockpit service is enabled and running
      ansible.builtin.systemd:
        name: cockpit
        enabled: yes
        state: started

    - name: Enable and start pmcd (Performance Metrics Collector Daemon)
      ansible.builtin.systemd:
        name: pmcd
        enabled: yes
        state: started

    - name: Enable and start pmproxy (for Prometheus export)
      ansible.builtin.systemd:
        name: pmproxy
        enabled: yes
        state: started

    - name: Ensure pmproxy is listening on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/pcp/pmproxy/pmproxy.options
        line: "-l :44322"
        create: yes
      notify: Restart pmproxy

# //TODO WHAT DOES THIS DO
  handlers:
    - name: Restart pmproxy
      ansible.builtin.systemd:
        name: pmproxy
        state: restarted