- name: Deploy Prometheus Operator
  hosts: servers
  become: yes
  tasks:
    - name: Check if monitoring namespace exists
      command: kubectl get namespace monitoring
      register: namespace_check
      ignore_errors: yes

    - name: Create monitoring namespace if not exists
      command: kubectl create namespace monitoring
      when: namespace_check.rc != 0

    - name: Install Prometheus CRDs
      command: kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd.yaml
      register: crd_apply
      failed_when: crd_apply.rc != 0