apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: grafana-selfsigned
  namespace: monitoring
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: nostalgiagame.go.ro
  dnsNames:
    - nostalgiagame.go.ro
  issuerRef:
    name: grafana-selfsigned
    kind: Issuer
