apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-mcp
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-mcp
  template:
    metadata:
      labels:
        app: azure-mcp
    spec:
      containers:
        - name: azure-mcp
          image: registry.server.robertgogete.eu/adx-mcp-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-mcp-secrets
                  key: AZURE_TENANT_ID
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-mcp-secrets
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-mcp-secrets
                  key: AZURE_CLIENT_SECRET
            - name: ADX_MCP_SERVER_TRANSPORT
              value: http
            - name: ADX_MCP_BIND_HOST
              value: "0.0.0.0"
            - name: ADX_MCP_BIND_PORT
              value: "3000"
            - name: ADX_CLUSTER_URL
              valueFrom:
                secretKeyRef:
                  name: azure-mcp-secrets
                  key: ADX_CLUSTER_URL
            - name: ADX_DATABASE
              valueFrom:
                secretKeyRef:
                  name: azure-mcp-secrets
                  key: ADX_DATABASE
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: azure-mcp
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: azure-mcp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000