apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-mcp
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-mcp
  template:
    metadata:
      labels:
        app: weather-mcp
    spec:
      containers:
        - name: weather-mcp
          image: registry.server.robertgogete.eu/mcp-weather:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: weather-mcp
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: weather-mcp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
