apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
kind: Secret
metadata:
  name: plex-claim-secret
  namespace: plex
stringData:
  PLEX_CLAIM_TOKEN: "changeme"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /storage/seagate-1tb/plex-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nostalgiagame.go.ro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          env:
            - name: TZ
              value: "Europe/Bucharest"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-claim-secret
                  key: PLEX_CLAIM_TOKEN
                  optional: true
          ports:
            - name: http
              containerPort: 32400
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 6Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-pvc
        - name: transcode
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
    - name: http
      port: 32400
      targetPort: 32400
      nodePort: 32400