apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector: {}
  scrapeConfigs:
    - job_name: "cockpit-pcp"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["your-server-ip:44322"]
