apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-ca-cert
  namespace: registry
spec:
  isCA: true
  commonName: registry-ca
  secretName: registry-ca-secret
  issuerRef:
    name: registry-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: registry-cert-issuer
  namespace: registry
spec:
  ca:
    secretName: registry-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
  namespace: registry
spec:
  secretName: registry-tls
  duration: 8760h # 1 year
  renewBefore: 360h
  commonName: nostalgiagame.go.ro
  dnsNames:
    - nostalgiagame.go.ro
  ipAddresses:
    - 192.168.1.186
  issuerRef:
    name: registry-cert-issuer
    kind: Issuer