name: Deploy K3s with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Secrets
        run: |
          [ -z "${{ secrets.SERVER_IP }}" ] && exit 1
          [ -z "${{ secrets.SERVER_USER }}" ] && exit 1
          [ -z "${{ secrets.SERVER_PASSWORD }}" ] && exit 1

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ansible-playbook -i inventory.ini playbook.yml
