name: Rollout Restart Keycloak

on:
  workflow_dispatch:

jobs:
  rollout-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Secrets
        run: test -n "${{ secrets.SERVER_IP }}" && test -n "${{ secrets.SERVER_USER }}" && test -n "${{ secrets.SERVER_PASSWORD }}"

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Rollout Restart Keycloak Deployment
        run: |
          echo "[servers]" > inventory.ini
          echo "k3s-master ansible_host=${{ secrets.SERVER_IP }} ansible_user=${{ secrets.SERVER_USER }} ansible_ssh_pass=${{ secrets.SERVER_PASSWORD }} ansible_become_pass=${{ secrets.SERVER_PASSWORD }}" >> inventory.ini
          ansible -i inventory.ini all -m shell -a 'kubectl rollout restart deployment/keycloak -n nostalgiagame' --become
